### ISSUE TITLE
Empty or invalid UTF-8 message

### ISSUE THREAD

**Issue by Soket1** [HexyeDEV/Telegram-Chatbot-Gpt4Free#1] opened 2023-05-30 11:55 UTC
Unhandled exception on handler
Traceback (most recent call last):
  File "C:\Python310\Lib\site-packages\telethon\client\updates.py", line 497, in _dispatch_update
    await callback(event)
  File "C:\GPT4FREE\main.py", line 91, in handler
    await msg.edit(result)
  File "C:\Python310\Lib\site-packages\telethon\tl\custom\message.py", line 815, in edit
    return await self._client.edit_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python310\Lib\site-packages\telethon\client\messages.py", line 1213, in edit_message
    msg = self._get_response_message(request, await self(request), entity)
                                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Python310\Lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python310\Lib\site-packages\telethon\client\users.py", line 84, in _call
    result = await future
             ^^^^^^^^^^^^
telethon.errors.rpcerrorlist.MessageEmptyError: Empty or invalid UTF-8 message was sent (caused by EditMessageRequest)

**Comment by HexyeDEV** [comment] 2023-05-31 08:56
could you please tell me how I could reproduce the error?

**Comment by Soket1** [comment] 2023-05-31 11:02
```
  try:
        result = await AiAgent(prompt, system_prompt)
        logger.info(f' prompt is {prompt}')
        logger.info(f' system prompt is {system_prompt}')
        logger.info(f'Editing message {msg.id}. Result is {result}')
        await msg.edit(result)
    except MessageEmptyError:
        print('Empty message, editing canceled')

```
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.network.mtprotosender:Handling RPC result for message 7239093824759814892
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
INFO:__main__: messages is [{'role': 'system', 'content': ''}, {'role': 'user', 'content': 'hello'}]
INFO:__main__: full text is
INFO:__main__: prompt is hello
INFO:__main__: system prompt is
INFO:__main__:Editing message 834. Result is
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 7239093830399698176 to EditMessageRequest (226a4a5e710)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 60 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 7239093830423707880 to MsgsAck (226a4a5f010)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 36 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.network.mtprotosender:Handling RPC result for message 7239093830399698176
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 7239093831064635196 to MsgsAck (226a4a5c2d0)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 36 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 7239093831084658540 to MsgsAck (226a4a5f310)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 36 bytes for sending
Empty message, editing canceled

When sending any message. 
**Today everything worked !** 
It looks like it was a temporary problem with the EvaGPT4 API.

**Comment by HexyeDEV** [comment] 2023-05-31 15:19
Do you still have such issue?

**Comment by HexyeDEV** [comment] 2023-05-31 15:48
Looks like this was caused by a too big payload. Shortened prompts, closing this issue for now.

**Comment by egcash** [comment] 2023-08-20 09:16
Unhandled exception on handler                                Traceback (most recent call last):                              File "/usr/local/lib/python3.10/dist-packages/telethon/client/updates.py", line 497, in _dispatch_update                      await callback(event)
  File "/root/Telegram-Chatbot-Gpt4Free/main.py", line 217, in handler                                                          await msg.edit(result)                                      File "/usr/local/lib/python3.10/dist-packages/telethon/tl/custom/message.py", line 815, in edit                               return await self._client.edit_message(                     File "/usr/local/lib/python3.10/dist-packages/telethon/client/messages.py", line 1213, in edit_message                        msg = self._get_response_message(request, await self(request), entity)                                                    File "/usr/local/lib/python3.10/dist-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)                                                           File "/usr/local/lib/python3.10/dist-packages/telethon/client/users.py", line 84, in _call                                    result = await future
telethon.errors.rpcerrorlist.MessageEmptyError: Empty or invalid UTF-8 message was sent (caused by EditMessageRequest)

**Comment by egcash** [comment] 2023-08-20 09:18
> Do you still have such issue?

Same issue

**Comment by HexyeDEV** [comment] 2023-08-25 19:12
Could be something with evagpt, will look into that

**Comment by egcash** [comment] 2023-08-26 01:29
If possible, try to include herc AI.

**Closed** 2023-09-17 08:41 UTC
